name: R-CMD-check

on:
  push:
    branches: [main, develop, rebuild-core]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release', bioc: '3.17'}
          - {os: ubuntu-22.04, r: 'devel', bioc: '3.18'}
          - {os: macOS-latest, r: 'release', bioc: '3.17'}
          - {os: windows-latest, r: 'release', bioc: '3.17'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          bioc-version: ${{ matrix.config.bioc }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Run namespace validation
        run: |
          Rscript -e "source('tests/scripts/validate_namespace.R'); validate_namespace()"

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true