"""Two executors over the one stage registry.

LocalExecutor runs the resolved stages in sequence in-process (laptop). SnakemakeExecutor
generates a Snakefile from the SAME registry whose rules shell out to ``microfgt _run-stage``
(HTCF batch via a Slurm profile). Neither re-encodes commands — that lives once in the
registry — so the two deployment contexts can't drift.
"""

from __future__ import annotations

from pathlib import Path

from microfgt.stages.model import artifact_paths
from microfgt.stages.registry import execute_stage


class LocalExecutor:
    """Run resolved stages sequentially in-process."""

    def run(self, stages, workdir, config, output=None) -> str:
        Path(workdir).mkdir(parents=True, exist_ok=True)
        for stage in stages:
            execute_stage(stage.id, workdir, config, output)
        return artifact_paths(workdir, config, output)["mudata"]


class SnakemakeExecutor:
    """Generate a Snakefile from the registry (real Slurm execution = HTCF validation IOU)."""

    def generate(self, stages, config_path, workdir, output=None) -> str:
        # config must be on disk so each `_run-stage` shell call can re-read it.
        from microfgt.stages.registry import provided_artifacts
        from microfgt.config import load_config

        config = load_config(config_path)
        paths = artifact_paths(workdir, config, output)
        provided = set(provided_artifacts(config))

        lines = [
            "# Generated by microFGT from the stage registry — do not edit by hand.",
            "# Each rule shells out to `microfgt _run-stage` so command logic lives once.",
            "",
            "rule all:",
            f'    input: "{paths["mudata"]}"',
            "",
        ]
        for stage in stages:
            ins = [paths[k] for k in stage.inputs]
            outs = [paths[k] for k in stage.outputs]
            shell = (
                f"microfgt _run-stage {stage.id} "
                f"--workdir {workdir} --config {config_path} --output {paths['mudata']}"
            )
            lines += [
                f"rule {stage.id}:",
                "    input: " + ", ".join(f'"{p}"' for p in ins),
                "    output: " + ", ".join(f'"{p}"' for p in outs),
                f'    shell: "{shell}"',
                "",
            ]
        # Provided (entry-point) artifacts are pre-existing inputs with no rule — noted only.
        if provided:
            lines.append("# Entry-point inputs (provided, not generated): " + ", ".join(sorted(provided)))
        return "\n".join(lines)

    def run(self, stages, config_path, workdir, output=None) -> str:
        """Write the Snakefile and return its path. Submitting it (Slurm) is the HTCF step."""
        Path(workdir).mkdir(parents=True, exist_ok=True)
        snakefile = Path(workdir) / "Snakefile"
        snakefile.write_text(self.generate(stages, config_path, workdir, output))
        return str(snakefile)
