"""The stage model — the single source of truth both executors consume.

A stage is a pure file->file step: ``(input artifact paths) -> command -> (output artifact
paths)``. That shape is simultaneously what a make-style local resolver needs and exactly a
Snakemake rule, so the local and cluster executors are two consumers of ONE registry rather
than two hand-maintained DAGs (no drift).

Artifacts are identified by key; generated artifacts get a deterministic path inside the run
workdir, provided artifacts (the entry point) keep their real paths.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

# Artifact key -> default filename inside the workdir. None = provided-only (an entry point
# input or the final output), never generated by a stage into the workdir.
ARTIFACT_FILENAMES: dict[str, str | None] = {
    "fastq_dir": None,               # provided: raw amplicon FASTQs
    "valencia_output": None,         # provided: an existing VALENCIA CSV
    "phyloseq_rds": None,            # provided: a phyloseq .rds (composition + taxonomy + CST)
    "phyloseq_cst": None,            # provided: signal to take CST from the phyloseq (= the .rds)
    "trimmed_reads": "trimmed",      # dir of primer-trimmed FASTQs
    "asv_table": "asv_table.csv",
    "asv_seqs": "asv_seqs.fasta",
    "quality_profile": "quality_profile.tsv",
    "speciateit_results": "speciateit/MC_order7_results.txt",
    "composition": "composition.h5ad",
    "cst": "cst.csv",
    "mudata": None,                  # the final target (= config 'output' / CLI -o)
}


@dataclass(frozen=True)
class Requirement:
    """An external prerequisite a stage needs (checked by ``microfgt check``)."""

    kind: str            # "binary" | "rpackage" | "path"
    name: str            # command name, R package name, or filesystem path
    hint: str = ""       # how to satisfy it, shown when missing


@dataclass
class StageContext:
    """Resolved paths + config handed to a stage at execution time."""

    workdir: Path
    artifacts: dict[str, str]   # artifact key -> resolved path
    config: dict

    def path(self, key: str) -> Path:
        return Path(self.artifacts[key])


@dataclass
class Stage:
    """One file->file step in the workflow."""

    id: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    run: Callable[[StageContext], None]
    requirements: Callable[[dict], list[Requirement]] = field(
        default=lambda cfg: []
    )


def artifact_paths(workdir, config: dict, output: str | None = None) -> dict[str, str]:
    """Map every artifact key to a concrete path: provided ones from config, the rest under
    the workdir. Both executors call this so they agree on every file location."""
    from microfgt.stages.registry import provided_artifacts

    paths = dict(provided_artifacts(config))
    target = output or config.get("output")
    if target:
        paths["mudata"] = str(target)
    workdir = Path(workdir)
    for key, filename in ARTIFACT_FILENAMES.items():
        if key not in paths and filename is not None:
            paths[key] = str(workdir / filename)
    return paths
