# Package build workflow for microFGT
# Simple workflow to check if the package can be built

name: Package Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Build Package
        run: |
          R CMD build .
          
      - name: Install Package from Source
        run: |
          PKG_FILE=$(ls -1t *.tar.gz | head -n 1)
          R CMD INSTALL ${PKG_FILE}
          
      - name: Check Basic Loading
        run: |
          Rscript -e 'library(microFGT); sessionInfo()'