# Test coverage workflow for microFGT
# Calculates test coverage and reports to codecov.io

name: test-coverage

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'CODEOWNERS'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/**'  # Skip when only updating workflows
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 4 * * 1' # Run weekly on Mondays at 4:00 UTC
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## Print out the test results
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package